from django.contrib import admin
from reports.models import *

# Register your models here.

admin.site.register(ReportCategory)
admin.site.register(ReportType)
admin.site.register(Ncpcr)
admin.site.register(ChildLabour)
admin.site.register(ParentingClinic)
admin.site.register(ParentingOutreach)
admin.site.register(ChildMarriage)
admin.site.register(Saranabalyam)
admin.site.register(ChildrenViolence)
admin.site.register(StateSponsorship)
admin.site.register(CentralSponsorship)
admin.site.register(AfterCareService)
admin.site.register(AfterCareChildrenCci)
admin.site.register(CrimeCommittedChildren)
admin.site.register(JuvenileJustice)
admin.site.register(Jja)
admin.site.register(Pocso)
admin.site.register(DeInstitutional)
admin.site.register(Jjb)
admin.site.register(InstitutionalCare)
admin.site.register(Cwc)
admin.site.register(InstitutionalCareProtection)
admin.site.register(Adoption)
admin.site.register(ChildProtection)
admin.site.register(CasesCwc)
admin.site.register(FosterCare)
admin.site.register(Repatriation)
admin.site.register(ResourcePerson)
admin.site.register(QprSupremeCourt)
admin.site.register(QprHighCourt)
