# Generated by Django 4.0.2 on 2022-08-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_ncpcr_appointment_of_inspection_committee_by_state_u_s_54_of_jj_act_2015_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ncpcr',
            old_name='inspections_conducted_by_inspection_committee_to_all_housing_facilities_of_children_u_s_54_2_of_jj_act_2015',
            new_name='all_housing_facilities_of_children_u_s_54_2_of_jj_act_2015',
        ),
        migrations.RenameField(
            model_name='ncpcr',
            old_name='appointment_of_inspection_committee_by_state_u_s_54_of_jj_act_2015',
            new_name='inspection_committee_by_state_u_s_54_of_jj_act_2015',
        ),
        migrations.RenameField(
            model_name='ncpcr',
            old_name='whether_juvenile_justice_fund_has_been_created_u_s_105_of_jj_act_2015',
            new_name='juvenile_justice_fund_has_been_created_u_s_105_of_jj_act_2015',
        ),
        migrations.RemoveField(
            model_name='ncpcr',
            name='whether_the_state_govt_evaluated_the_functioning_of_jjb_cwc_sjpu_regd_or_recognized_institutions_u_s_55_1_of_jj_act_2015',
        ),
        migrations.AddField(
            model_name='ncpcr',
            name='children_in_place_of_safety',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncpcr',
            name='jjb_cwc_sjpu_regd_institutions_u_s_55_1_of_jj_act_2015',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncpcr',
            name='special_home_u_s_48_of_the_jj_act_2015',
            field=models.IntegerField(default=0),
        ),
    ]
