# Generated by Django 4.0.2 on 2022-08-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_qprhighcourt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qprhighcourt',
            name='age_group_15_18_childern_in_rci_16_a',
        ),
        migrations.RemoveField(
            model_name='qprhighcourt',
            name='age_group_15_18_childern_staying_rci_16_b',
        ),
    ]
