# Generated by Django 4.0.2 on 2022-08-31 12:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_spu_posco_vac_in_key_st_and_al_bo_sanctioned_positions_12_qprhighcourt_spu_pocso_vac_in_key_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncpcr',
            name='name',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
    ]
