# Generated by Django 4.0.2 on 2022-09-02 03:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_ncpcr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprhighcourt',
            name='name',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='qprsupremecourt',
            name='name',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
    ]
