# Generated by Django 4.0.2 on 2022-09-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_qprhighcourt_name_qprsupremecourt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceperson',
            name='no_of_sesson_demanded_expert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceperson',
            name='no_of_sesson_demanded_interpretor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceperson',
            name='no_of_sesson_demanded_special_educator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceperson',
            name='no_of_sesson_demanded_support_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceperson',
            name='no_of_sesson_demanded_translator',
            field=models.IntegerField(default=0),
        ),
    ]
