# Generated by Django 4.0.2 on 2022-09-14 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0011_resourceperson_no_of_sesson_demanded_expert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesCwc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jja_total_cases_cumulative', models.IntegerField(default=0)),
                ('jja_total_cases_current_quarter', models.IntegerField(default=0)),
                ('jja_fir_registered_cumulative', models.IntegerField(default=0)),
                ('jja_fir_registered_current_quarter', models.IntegerField(default=0)),
                ('jja_produced_before_cwc_cumulative', models.IntegerField(default=0)),
                ('jja_produced_before_cwc_current_quarter', models.IntegerField(default=0)),
                ('jja_who_avail_service_support_person_cumulative', models.IntegerField(default=0)),
                ('jja_who_avail_service_support_person_current_quarter', models.IntegerField(default=0)),
                ('jja_expert_service_cumulative', models.IntegerField(default=0)),
                ('jja_expert_service_current_quarter', models.IntegerField(default=0)),
                ('jja_counselling_cumulative', models.IntegerField(default=0)),
                ('jja_counselling_current_quarter', models.IntegerField(default=0)),
                ('jja_free_legal_aid_cumulative', models.IntegerField(default=0)),
                ('jja_free_legal_aid_current_quarter', models.IntegerField(default=0)),
                ('jja_victim_compensation_cumulative', models.IntegerField(default=0)),
                ('jja_victim_compensation_current_quarter', models.IntegerField(default=0)),
                ('jja_institutional_support_cumulative', models.IntegerField(default=0)),
                ('jja_institutional_support_current_quarter', models.IntegerField(default=0)),
                ('pocso_total_cases_cumulative', models.IntegerField(default=0)),
                ('pocso_total_cases_current_quarter', models.IntegerField(default=0)),
                ('pocso_fir_registered_cumulative', models.IntegerField(default=0)),
                ('pocso_fir_registered_current_quarter', models.IntegerField(default=0)),
                ('pocso_produced_before_cwc_cumulative', models.IntegerField(default=0)),
                ('pocso_produced_before_cwc_current_quarter', models.IntegerField(default=0)),
                ('pocso_who_avail_service_support_person_cumulative', models.IntegerField(default=0)),
                ('pocso_who_avail_service_support_person_current_quarter', models.IntegerField(default=0)),
                ('pocso_expert_service_cumulative', models.IntegerField(default=0)),
                ('pocso_expert_service_current_quarter', models.IntegerField(default=0)),
                ('pocso_counselling_cumulative', models.IntegerField(default=0)),
                ('pocso_counselling_current_quarter', models.IntegerField(default=0)),
                ('pocso_free_legal_aid_cumulative', models.IntegerField(default=0)),
                ('pocso_free_legal_aid_current_quarter', models.IntegerField(default=0)),
                ('pocso_victim_compensation_cumulative', models.IntegerField(default=0)),
                ('pocso_victim_compensation_current_quarter', models.IntegerField(default=0)),
                ('pocso_institutional_support_cumulative', models.IntegerField(default=0)),
                ('pocso_institutional_support_current_quarter', models.IntegerField(default=0)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CasesCwc',
            },
        ),
    ]
