# Generated by Django 4.0.2 on 2022-09-26 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0012_casescwc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentingOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outreach_camps_held_during_the_month', models.IntegerField(default=0)),
                ('panchayaths_covered_during_the_month', models.IntegerField(default=0)),
                ('clients_attended_during_the_month', models.IntegerField(default=0)),
                ('parents_attended_during_the_month', models.IntegerField(default=0)),
                ('children_attended_during_the_month', models.IntegerField(default=0)),
                ('issues_identified_behavioural_during_the_month', models.IntegerField(default=0)),
                ('issues_identified_emotional_during_the_month', models.IntegerField(default=0)),
                ('issues_identified_somatic_during_the_month', models.IntegerField(default=0)),
                ('issues_identified_interpersonal_during_the_month', models.IntegerField(default=0)),
                ('issues_identified_cognitive_during_the_month', models.IntegerField(default=0)),
                ('issues_identified_family_discord_during_the_month', models.IntegerField(default=0)),
                ('referrals_done_during_the_month', models.IntegerField(default=0)),
                ('awareness_classes_during_the_month', models.IntegerField(default=0)),
                ('outreach_camps_held_up_to_last_month', models.IntegerField(default=0)),
                ('panchayaths_covered_up_to_last_month', models.IntegerField(default=0)),
                ('clients_attended_up_to_last_month', models.IntegerField(default=0)),
                ('parents_attended_up_to_last_month', models.IntegerField(default=0)),
                ('children_attended_up_to_last_month', models.IntegerField(default=0)),
                ('issues_identified_behavioural_up_to_last_month', models.IntegerField(default=0)),
                ('issues_identified_emotional_up_to_last_month', models.IntegerField(default=0)),
                ('issues_identified_somatic_up_to_last_month', models.IntegerField(default=0)),
                ('issues_identified_interpersonal_up_to_last_month', models.IntegerField(default=0)),
                ('issues_identified_cognitive_up_to_last_month', models.IntegerField(default=0)),
                ('issues_identified_family_discord_up_to_last_month', models.IntegerField(default=0)),
                ('referrals_done_up_to_last_month', models.IntegerField(default=0)),
                ('awareness_classes_up_to_last_month', models.IntegerField(default=0)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parenting_outreach',
            },
        ),
    ]
