# Generated by Django 4.0.2 on 2022-09-28 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0013_parentingoutreach'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentingClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clients_attended_the_clinic', models.IntegerField(default=0)),
                ('new_cases', models.IntegerField(default=0)),
                ('follow_up_cases', models.IntegerField(default=0)),
                ('parents_attended_cumulative', models.IntegerField(default=0)),
                ('parents_attended_on_the_day', models.IntegerField(default=0)),
                ('children_attended_cumulative', models.IntegerField(default=0)),
                ('children_attended_on_the_day', models.IntegerField(default=0)),
                ('behavioural_cumulative', models.IntegerField(default=0)),
                ('behavioural_on_the_day', models.IntegerField(default=0)),
                ('emotional_cumulative', models.IntegerField(default=0)),
                ('emotional_on_the_day', models.IntegerField(default=0)),
                ('somatic_cumulative', models.IntegerField(default=0)),
                ('somatic_on_the_day', models.IntegerField(default=0)),
                ('interpersonal_cumulative', models.IntegerField(default=0)),
                ('interpersonal_on_the_day', models.IntegerField(default=0)),
                ('cognitive_cumulative', models.IntegerField(default=0)),
                ('cognitive_on_the_day', models.IntegerField(default=0)),
                ('family_discord_cumulative', models.IntegerField(default=0)),
                ('family_discord_on_the_day', models.IntegerField(default=0)),
                ('referrals_done_counsellor_cumulative', models.IntegerField(default=0)),
                ('referrals_done_counsellor_on_the_day', models.IntegerField(default=0)),
                ('walk_ins_cumulative', models.IntegerField(default=0)),
                ('walk_ins_on_the_day', models.IntegerField(default=0)),
                ('referral_cases_cumulative', models.IntegerField(default=0)),
                ('referral_cases_on_the_day', models.IntegerField(default=0)),
                ('awws_cumulative', models.IntegerField(default=0)),
                ('awws_on_the_day', models.IntegerField(default=0)),
                ('teachers_cumulative', models.IntegerField(default=0)),
                ('teachers_on_the_day', models.IntegerField(default=0)),
                ('police_cumulative', models.IntegerField(default=0)),
                ('police_on_the_day', models.IntegerField(default=0)),
                ('asha_workers_cumulative', models.IntegerField(default=0)),
                ('asha_workers_on_the_day', models.IntegerField(default=0)),
                ('local_leaders_cumulative', models.IntegerField(default=0)),
                ('local_leaders_on_the_day', models.IntegerField(default=0)),
                ('others_cumulative', models.IntegerField(default=0)),
                ('others_on_the_day', models.IntegerField(default=0)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parenting_clinic',
            },
        ),
    ]
