# Generated by Django 4.0.2 on 2022-10-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_parentingclinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmarriage',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='childmarriage',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
    ]
