# Generated by Django 4.0.2 on 2022-10-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_childmarriage_month_childmarriage_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='adoption',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aftercarechildrencci',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aftercarechildrencci',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aftercareservice',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='aftercareservice',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='casescwc',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='casescwc',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='centralsponsorship',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='centralsponsorship',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='childlabour',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='childlabour',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='childprotection',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='childprotection',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='childrenviolence',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='childrenviolence',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimecommittedchildren',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='crimecommittedchildren',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cwc',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cwc',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deinstitutional',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deinstitutional',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fostercare',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='fostercare',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='institutionalcare',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='institutionalcare',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='institutionalcareprotection',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='institutionalcareprotection',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='jja',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='jja',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='jjb',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='jjb',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='juvenilejustice',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='juvenilejustice',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ncpcr',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ncpcr',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parentingclinic',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parentingclinic',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parentingoutreach',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='parentingoutreach',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pocso',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pocso',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='qprhighcourt',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='qprhighcourt',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='qprsupremecourt',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='qprsupremecourt',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='repatriation',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='repatriation',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='resourceperson',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='resourceperson',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='saranabalyam',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='saranabalyam',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='statesponsorship',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='statesponsorship',
            name='year',
            field=models.CharField(default='', max_length=120),
        ),
    ]
