# Generated by Django 4.0.2 on 2022-10-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_rename_cci_female_childrenviolence_abetment_female_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='abetment_female',
            new_name='abetment_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='abetment_male',
            new_name='abetment_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='buying_girls_female',
            new_name='buying_girls_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='buying_girls_male',
            new_name='buying_girls_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='exposure_female',
            new_name='exposure_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='exposure_male',
            new_name='exposure_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='foeticide_female',
            new_name='foeticide_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='foeticide_male',
            new_name='foeticide_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='kidnapping_female',
            new_name='kidnapping_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='kidnapping_male',
            new_name='kidnapping_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='other_crimes_female',
            new_name='other_crimes_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='other_crimes_male',
            new_name='other_crimes_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='procuration_female',
            new_name='procuration_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='procuration_male',
            new_name='procuration_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='prohibition_female',
            new_name='prohibition_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='prohibition_male',
            new_name='prohibition_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='selling_girls_female',
            new_name='selling_girls_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='selling_girls_male',
            new_name='selling_girls_cci_male',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='total_female',
            new_name='total_cci_female',
        ),
        migrations.RenameField(
            model_name='childrenviolence',
            old_name='total_male',
            new_name='total_cci_male',
        ),
    ]
