# Generated by Django 4.0.2 on 2022-10-28 07:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_rename_abetment_female_childrenviolence_abetment_cci_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='aftercarechildrencci',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='aftercareservice',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='casescwc',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='centralsponsorship',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='childlabour',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='childmarriage',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='childprotection',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='childrenviolence',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='crimecommittedchildren',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='cwc',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='deinstitutional',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='fostercare',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='institutionalcare',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='institutionalcareprotection',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='jja',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='jjb',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='parentingclinic',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='parentingoutreach',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='repatriation',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='resourceperson',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='saranabalyam',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
        migrations.AddField(
            model_name='statesponsorship',
            name='username',
            field=models.CharField(default=accounts.models.User, max_length=120),
        ),
    ]
