# Generated by Django 4.0.2 on 2022-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_adoption_username_aftercarechildrencci_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftercarechildrencci',
            name='vocational_or_placement_training_female_current_quarter',
            field=models.IntegerField(default=0),
        ),
    ]
