# Generated by Django 4.0.2 on 2022-11-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_aftercarechildrencci_vocational_or_placement_training_female_current_quarter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentingclinic',
            old_name='clients_attended_the_clinic',
            new_name='clients_attended_the_clinic_cumulative',
        ),
        migrations.RenameField(
            model_name='parentingclinic',
            old_name='follow_up_cases',
            new_name='clients_attended_the_clinic_during_the_month',
        ),
        migrations.RenameField(
            model_name='parentingclinic',
            old_name='new_cases',
            new_name='follow_up_cases_cumulative',
        ),
        migrations.AddField(
            model_name='parentingclinic',
            name='follow_up_cases_during_the_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentingclinic',
            name='new_cases_cumulative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentingclinic',
            name='new_cases_during_the_month',
            field=models.IntegerField(default=0),
        ),
    ]
