# Generated by Django 4.0.2 on 2022-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_rename_clients_attended_the_clinic_parentingclinic_clients_attended_the_clinic_cumulative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentingoutreach',
            name='people_attended_awareness_class_during_the_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentingoutreach',
            name='people_attended_awareness_up_to_last_month',
            field=models.IntegerField(default=0),
        ),
    ]
