# Generated by Django 4.0.2 on 2022-11-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_parentingoutreach_people_attended_awareness_class_during_the_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ncpcr',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='qprhighcourt',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='qprsupremecourt',
            old_name='name',
            new_name='username',
        ),
    ]
