# Generated by Django 4.0.2 on 2022-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_rename_name_ncpcr_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qprsupremecourt',
            name='working_strength_of_jjb_staff_in_the_state',
            field=models.IntegerField(default=0),
        ),
    ]
